# _config.yml
exclude:
  - "node_modules/"
  - "**/node_modules/"
  - "voice-recorder-app/"
  - "mern-crash-course/"
  - "*.json"
  - "*.js"
  - "*.ts"
  - "package*.json"
  - "yarn.lock"
  - "package-lock.json"
  - "*.config.js"
