# # _config.yml
# exclude:
#   - "node_modules/"
#   - "**/node_modules/"
#   - "mern-crash-course/"
#   - "*.json"
#   - "*.js"
#   - "*.ts"
#   - "package*.json"
#   - "yarn.lock"
#   - "package-lock.json"
#   - "*.config.js"

# # Keep files included but disable Liquid processing for certain paths
# defaults:
#   - scope:
#       path: "voice-recorder-app"
#       type: files
#     values:
#       liquid: false
#   - scope:
#       path: "mern-crash-course"
#       type: files
#     values:
#       liquid: false
#   - scope:
#       path: "**/node_modules"
#       type: files
#     values:
#       liquid: false
